// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfPlAfLBiGzPlfTbM0QpiYp-nZVOCsS0',
    appId: '1:531662378761:web:370f785baf188cbf2ca5d8',
    messagingSenderId: '531662378761',
    projectId: 'instafeed-1e278',
    authDomain: 'instafeed-1e278.firebaseapp.com',
    storageBucket: 'instafeed-1e278.appspot.com',
    measurementId: 'G-TR61H49F55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA83PkYYNCQ22wBUGE0qKytaDiaUc6Tx6s',
    appId: '1:531662378761:android:29558c2fbef907372ca5d8',
    messagingSenderId: '531662378761',
    projectId: 'instafeed-1e278',
    storageBucket: 'instafeed-1e278.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzoFia4YDyYVZRoP5keMuaU3rwybijwNo',
    appId: '1:531662378761:ios:5499df9a66dd184c2ca5d8',
    messagingSenderId: '531662378761',
    projectId: 'instafeed-1e278',
    storageBucket: 'instafeed-1e278.appspot.com',
    iosBundleId: 'com.example.instagramPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzoFia4YDyYVZRoP5keMuaU3rwybijwNo',
    appId: '1:531662378761:ios:98bc31e40497e5ee2ca5d8',
    messagingSenderId: '531662378761',
    projectId: 'instafeed-1e278',
    storageBucket: 'instafeed-1e278.appspot.com',
    iosBundleId: 'com.example.instagramPro.RunnerTests',
  );
}
